export type Quiz = {
    question: string;
    options: [string, string];
    answerIndex: number;
};

export const QUIZ_BANK: Quiz[] = [
    { question: "학술 논문에서 다른 사람의 아이디어를 출처 없이 사용하는 것은?", options: ["표절", "참조"], answerIndex: 0 },
    { question: "연구의 객관성을 유지하기 위해 가장 중요한 것은?", options: ["편향 배제", "결과 조작"], answerIndex: 0 },
    { question: "실험 결과를 기록할 때 가장 적절한 방법은?", options: ["데이터 선별 기록", "모든 데이터 기록"], answerIndex: 1 },
    { question: "설문 조사를 할 때 응답자의 익명성을 보장해야 하는 이유는?", options: ["연구 윤리 준수", "설문지 비용 절감"], answerIndex: 0 },
    { question: "서론에서 다루어야 할 핵심 내용은?", options: ["연구의 필요성", "실험 도구 목록"], answerIndex: 0 },
    { question: "참고문헌 리스트를 작성하는 주된 목적은?", options: ["본문의 길이를 늘리기 위해", "신뢰성 확보와 출처 표기"], answerIndex: 1 },
    { question: "가설을 설정할 때의 특징은?", options: ["검증 가능해야 함", "무조건 참이어야 함"], answerIndex: 0 },
    { question: "양적 연구에서 주로 사용하는 도구는?", options: ["통계 분석", "심층 면담"], answerIndex: 0 },
    { question: "질적 연구의 특징으로 옳은 것은?", options: ["수치화된 결과 중시", "현상의 의미와 맥락 중시"], answerIndex: 1 },
    { question: "연구 보고서의 제목은 어떠해야 하는가?", options: ["최대한 모호하게", "명확하고 구체적으로"], answerIndex: 1 },
    { question: "피어 리뷰(Peer Review)의 의미는?", options: ["동료 전문가의 심사", "스스로 자신의 글 검토"], answerIndex: 0 },
    { question: "데이터 시각화를 위해 그래프를 사용할 때 주의점은?", options: ["왜곡 없는 표현", "화려한 색상 사용"], answerIndex: 0 },
    { question: "연구 대상이 사람인 경우 반드시 받아야 하는 서류는?", options: ["연구 참여 동의서", "건강 검진 기록부"], answerIndex: 0 },
    { question: "결론 섹션에서 해야 할 일은?", options: ["새로운 데이터 제시", "연구 결과 요약 및 제언"], answerIndex: 1 },
    { question: "초록(Abstract)은 대략 어느 정도 분량이 적당한가?", options: ["10페이지 내외", "200~300단어 내외"], answerIndex: 1 },
    { question: "실험군과 대조군을 나누는 이유는?", options: ["실험 변인의 효과 확인", "실험 참여 인원 증가"], answerIndex: 0 },
    { question: "논문의 '방법론' 섹션에 포함될 내용은?", options: ["연구 수행 절차", "연구자의 일기"], answerIndex: 0 },
    { question: "상관관계와 인과관계는 같은 의미인가?", options: ["네", "아니요"], answerIndex: 1 },
    { question: "연구의 제한점이란?", options: ["연구자가 게을러서 못한 일", "연구 설계상 한계 및 범위"], answerIndex: 1 },
    { question: "각주(Footnote)의 역할은?", options: ["보충 설명 및 출처 제시", "본문 숨기기"], answerIndex: 0 },
    { question: "표본(Sample)을 추출할 때 가장 좋은 방법은?", options: ["무작위 추출", "지인 위주 추출"], answerIndex: 0 },
    { question: "연구 보고서에서 '논의(Discussion)' 섹션의 역할은?", options: ["결과에 대한 해석 및 의미 부여", "단순히 수치 나열"], answerIndex: 0 },
    { question: "신뢰도(Reliability)란 무엇을 의미하는가?", options: ["측정 결과의 일관성", "측정 도구의 가격"], answerIndex: 0 },
    { question: "타당도(Validity)란 무엇을 의미하는가?", options: ["측정하고자 하는 것을 정확히 측정했는가", "검사 시간이 짧은가"], answerIndex: 0 },
    { question: "중복 게재(Duplicate Publication)는 연구 윤리에 어긋나는가?", options: ["네", "아니요"], answerIndex: 0 },
    { question: "연구비 지원 출처를 밝혀야 하는 이유는?", options: ["이해 상충 방지 및 투명성", "기부자 자랑을 위해"], answerIndex: 0 },
    { question: "설문 문항을 구성할 때 피해야 할 것은?", options: ["유도 질문", "객관적 문항"], answerIndex: 0 },
    { question: "실험에서 '독립 변수'란?", options: ["결과에 영향을 주는 변수", "결과로 나타나는 변수"], answerIndex: 0 },
    { question: "실험에서 '종속 변수'란?", options: ["결과에 영향을 주는 변수", "관찰하거나 측정하는 결과 변수"], answerIndex: 1 },
    { question: "문헌 연구(Literature Review)의 시점은?", options: ["연구 시작 전", "연구 완료 후"], answerIndex: 0 },
    { question: "아카이브(Archive)의 기능은?", options: ["자료의 보존 및 기록", "광고 게시판"], answerIndex: 0 },
    { question: "오픈 액세스(Open Access) 논문의 특징은?", options: ["비싼 구독료 지불", "누구나 자유롭게 열람 가능"], answerIndex: 1 },
    { question: "연구자의 정직성이 중요한 이유는?", options: ["개인적 명예를 위해", "과학적 지식 발전을 위해"], answerIndex: 1 },
    { question: "IRB(연구윤리심의위원회)의 주요 역할은?", options: ["연구 대상자 보호", "연구비 입금 확인"], answerIndex: 0 },
    { question: "보고서에서 '표(Table)'의 번호와 제목 위치는?", options: ["표의 하단", "표의 상단"], answerIndex: 1 },
    { question: "보고서에서 '그림(Figure)'의 번호와 제목 위치는?", options: ["그림의 하단", "그림의 상단"], answerIndex: 0 },
    { question: "이차 자료 분석이란?", options: ["이미 존재하는 데이터를 재분석", "직접 실험하여 얻은 데이터 분석"], answerIndex: 0 },
    { question: "연구의 필요성을 기술할 때 유용한 방식은?", options: ["기존 연구의 공백 제시", "자신의 감정 호소"], answerIndex: 0 },
    { question: "인용(Citation)을 할 때 직접 인용이란?", options: ["원문을 그대로 가져와 따옴표 표시", "내용을 요약하여 자신의 문장으로 씀"], answerIndex: 0 },
    { question: "인용(Citation)을 할 때 간접 인용이란?", options: ["원문을 그대로 가져옴", "원문 내용을 자신의 말로 바꾸어 씀"], answerIndex: 1 },
    { question: "데이터의 '중앙값'이란?", options: ["크기순으로 나열했을 때 한가운데 값", "가장 자주 나타나는 값"], answerIndex: 0 },
    { question: "데이터의 '최빈값'이란?", options: ["가장 평균적인 값", "가장 빈번하게 나타나는 값"], answerIndex: 1 },
    { question: "질적인 데이터 분석에서 '코딩'이란?", options: ["컴퓨터 프로그래밍", "데이터에 의미 있는 범주 부여"], answerIndex: 1 },
    { question: "연구의 제목을 정할 때 키워드는 어느 쪽에 배치하는 것이 좋은가?", options: ["가장 앞부분", "제목에 키워드 안 넣기"], answerIndex: 0 },
    { question: "보고서의 가독성을 높이려면?", options: ["복잡한 문장 사용", "명확한 문단 구분 및 소제목 활용"], answerIndex: 1 },
    { question: "연구 결과가 가설과 다르게 나왔을 때 행동은?", options: ["데이터 수정", "결과 그대로를 보고하고 이유 분석"], answerIndex: 1 },
    { question: "고등학생 탐구 보고서에서 가장 권장되는 태도는?", options: ["거창한 결과물 집착", "과정의 성실함과 비판적 사고"], answerIndex: 1 },
    { question: "데이터 정제(Data Cleaning)란?", options: ["오류나 결측치 처리 과정", "데이터를 삭제하여 원하는 결과 만들기"], answerIndex: 0 },
    { question: "연구의 '재현성'이란?", options: ["같은 방법으로 수행 시 같은 결과 도출", "연구자가 다시 한 번 설명하기"], answerIndex: 0 },
    { question: "설문 조사에서 '리커트 척도'란?", options: ["예/아니오 답변", "전혀 그렇지 않다~매우 그렇다 등의 5~7점 척도"], answerIndex: 1 },
    { question: "사전 연구(Pilot Study)의 목적은?", options: ["본 연구 전 미리 소규모로 테스트", "연구비 횡령"], answerIndex: 0 },
    { question: "연구자의 주관이 개입되지 않도록 하는 것을 무엇이라 하는가?", options: ["가치 중립성", "가치 함축성"], answerIndex: 0 },
    { question: "수치화된 데이터를 다루는 학문 분야는?", options: ["문학", "통계학"], answerIndex: 1 },
    { question: "검색 엔진에서 학술 자료를 찾기에 더 적합한 곳은?", options: ["구글 학술 검색", "유튜브"], answerIndex: 0 },
    { question: "학술지에 논문을 투고하면 받는 프로세스는?", options: ["게시물 삭제", "심사(Review)"], answerIndex: 1 },
    { question: "참고문헌 스타일 중 하나인 APA는 주로 어느 분야에서 쓰이는가?", options: ["예술/디자인", "심리학/사회과학"], answerIndex: 1 },
    { question: "주제를 선정할 때 고려해야 할 '현실성'이란?", options: ["이미 누구나 아는 주제 선정", "시간과 예산 내 완수 가능성"], answerIndex: 1 },
    { question: "과학적 방법의 첫 번째 단계는?", options: ["데이터 분석", "관찰 및 문제 제기"], answerIndex: 1 },
    { question: "조사 대상의 특징을 잘 반영하도록 뽑은 집단을 무엇이라 하는가?", options: ["표본", "모집단"], answerIndex: 0 },
    { question: "전체 조사 대상을 무엇이라 하는가?", options: ["표본", "모집단"], answerIndex: 1 },
    { question: "연구의 '창의성'은 무엇을 의미하는가?", options: ["기존과 다른 새로운 시각이나 방법 제시", "화려한 그림 그리기"], answerIndex: 0 },
    { question: "생활기록부용 보고서 작성 시 주의할 점은?", options: ["사실에 기반한 활동 요약", "거짓 경험 기록"], answerIndex: 0 },
    { question: "고교 탐구에서 교과서 개념을 활용하는 이유는?", options: ["교과 연계성 확인", "페이지 채우기용"], answerIndex: 0 },
    { question: "토론이나 면담 자료를 텍스트로 옮기는 작업은?", options: ["전사(Transcription)", "복사(Copying)"], answerIndex: 0 },
    { question: "연구 가설이 기각(Rejected)되었다는 말의 뜻은?", options: ["가설이 증명되지 않음", "가설이 채택됨"], answerIndex: 0 },
    { question: "가설이 채택(Accepted)되었다는 말의 뜻은?", options: ["데이터가 가설을 지지함", "가설이 틀림"], answerIndex: 0 },
    { question: "탐구 보고서의 적절한 어조(Tone)는?", options: ["감성적이고 주관적", "객관적이고 논리적"], answerIndex: 1 },
    { question: "참고한 문헌의 제목을 이탤릭체로 표기하는 방식은?", options: ["보통 논문 표기 규칙", "연구자의 자유"], answerIndex: 0 },
    { question: "데이터의 '분산'이나 '표준편차'가 의미하는 것은?", options: ["데이터가 퍼져 있는 정도", "데이터의 합계"], answerIndex: 0 },
    { question: "측정 도구의 일관성을 뜻하는 용어는?", options: ["신뢰도", "타당도"], answerIndex: 0 },
    { question: "연구 문제를 설정할 때 '왜?'라는 질문이 중요한 이유는?", options: ["연구의 인과관계 탐구", "단순 사실 확인"], answerIndex: 0 },
    { question: "연구 계획서(Proposal)의 작성 시점은?", options: ["연구 시작 전", "연구 완료 후"], answerIndex: 0 },
    { question: "동료 평가(Peer Review) 과정에서 '수정 권고'란?", options: ["논문을 버리라는 뜻", "보완해서 다시 제출하라는 뜻"], answerIndex: 1 },
    { question: "연구 결과를 발표할 때 포스터 세션의 장점은?", options: ["일대일 자유로운 피드백 공유", "발표 시간이 매우 길다"], answerIndex: 0 },
    { question: "인용(Citation) 누락을 방지하는 가장 좋은 습관은?", options: ["읽는 즉시 서지 정보 기록", "나중에 한꺼번에 찾기"], answerIndex: 0 },
    { question: "연구 보고서 내 '부록(Appendix)'에 넣는 자료는?", options: ["참고문헌 리스트", "본문에 넣기엔 너무 큰 설문지나 기초 데이터"], answerIndex: 1 },
    { question: "선행 연구 조사를 통해 얻을 수 있는 이점은?", options: ["중복 연구 방지 및 이론적 근거 확보", "잠을 더 잘 수 있다"], answerIndex: 0 },
    { question: "온라인 설문 폼(Google Forms 등) 사용 시 장점은?", options: ["데이터 자동 정리가 용이함", "참가자가 직접 손으로 써야 함"], answerIndex: 0 },
    { question: "실험 오류를 줄이기 위해 반복 실험을 하는 이유는?", options: ["결과의 정확성 및 신뢰성 증대", "실험 도구 손상 확인"], answerIndex: 0 },
    { question: "데이터가 '정규 분포'를 따르는지 확인하는 이유는?", options: ["다양한 통계 분석 기법 적용 가능 여부 판별", "모양이 예쁘게 나오기 위해"], answerIndex: 0 },
    { question: "연구 대상과 직접 만나 대화하며 데이터를 얻는 방법은?", options: ["면담법", "질문지법"], answerIndex: 0 },
    { question: "조사원이 개입하지 않고 대상자의 행동을 관찰하는 방법은?", options: ["관찰법", "실험법"], answerIndex: 0 },
    { question: "연구의 '객관성' 확보를 위해 필요한 태도는?", options: ["자신의 편견 경계", "친한 사람 의견 따르기"], answerIndex: 0 },
    { question: "연구 일지의 장점은?", options: ["연구 전 과정을 기록하여 반성적 탐구 가능", "심심풀이용"], answerIndex: 0 },
    { question: "참고문헌 표기 중 'et al.'은 무엇을 뜻하는가?", options: ["외 그 외 저자들", "본인이 직접 쓴 글"], answerIndex: 0 },
    { question: "연구 결과의 '일반화'란?", options: ["특정 사례의 결과를 전체 집단에 적용", "모든 사람이 동의한다는 뜻"], answerIndex: 0 },
    { question: "연구 결과를 왜곡하여 보고하는 행위를 무엇이라 하는가?", options: ["변조", "참조"], answerIndex: 0 },
    { question: "존재하지 않는 데이터를 만들어내는 행위는?", options: ["위조", "활용"], answerIndex: 0 },
    { question: "연구에서 '제한적 범위'를 설정하는 이유는?", options: ["연구의 구체성 및 집중도 향상", "하기 싫어서 범위를 좁힘"], answerIndex: 0 },
    { question: "자료 수집 시 '무응답' 처리는 어떻게 하는가?", options: ["대충 아무거나 채움", "결측치로 처리하거나 제외"], answerIndex: 1 },
    { question: "연구 가설 설정 시 '귀무 가설'의 의미는?", options: ["차이가 없거나 효과가 없다는 가설", "반드시 차이가 있다는 가설"], answerIndex: 0 },
    { question: "연구 가설 설정 시 '대립 가설'의 의미는?", options: ["효과가 없다는 가설", "연구자가 입증하고자 하는 가설"], answerIndex: 1 },
    { question: "데이터 분석 시 'p-value'가 주로 의미하는 것은?", options: ["결과의 유의 확률", "데이터의 개수"], answerIndex: 0 },
    { question: "연구 보고서의 마지막 문장은 대개 어떤 내용인가?", options: ["연구의 가치 재강조 및 향후 과제", "그냥 끝"], answerIndex: 0 },
    { question: "인용 스타일 중 'Chicaco 스타일'의 특징은?", options: ["각주(Footnote) 활용 중시", "인용 안 하기"], answerIndex: 0 },
    { question: "탐구 주제가 너무 광범위할 때 생기는 문제는?", options: ["연구가 깊이 있게 진행되지 못함", "너무 빨리 끝남"], answerIndex: 0 },
    { question: "수학적 모델링의 목적은?", options: ["현상을 수학식으로 표현하여 예측 및 이해", "복잡하게 보이기 위해"], answerIndex: 0 },
    { question: "질문지법에서 '폐쇄형 질문'이란?", options: ["이야기를 길게 쓰는 질문", "객관식처럼 응답 범위가 정해진 질문"], answerIndex: 1 },
    { question: "질문지법에서 '개방형 질문'이란?", options: ["주관식으로 자유롭게 응답하는 질문", "예/아니오로 답하는 질문"], answerIndex: 0 },
    { question: "연구자의 '윤리 선서'는 누구를 위한 것인가?", options: ["과학 공동체와 인류를 위한 약속", "부모님을 위한 약속"], answerIndex: 0 },
    { question: "탐구 보고서 작성시 수식 입력기는 무엇을 사용하는가?", options: ["LaTeX (또는 한글 수식 편집기)", "그림판"], answerIndex: 0 },
    { question: "학술 연구에서 데이터 공유의 장점은?", options: ["연구 투명성 및 지식 향상", "자신의 아이디어 뺏기기"], answerIndex: 0 },
    { question: "데이터 샘플링에서 '비확률 추출'의 단점은?", options: ["대표성이 떨어질 수 있음", "샘플링 비용이 비쌈"], answerIndex: 0 }
];
